on: [push]

name: Build and run demo

jobs:
  build:
    name: Build and run demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - run: make reproduce